"""
Caption styles definitions matching Captionizer presets.
Includes typography, colors, animations, and preview markup.
"""

STYLES = [
    {
        "id": "style_11",
        "name": "Editorial Hybrid",
        "tagline": "Modern editorial sans with Instrument Serif italic glow",
        "description": "Bold clean text with glowing italic serif emphasis words. As seen in top creator clips.",
        "font_family_base": "'Inter', 'SF Pro Display', -apple-system, sans-serif",
        "font_family_emphasis": "'Instrument Serif', Georgia, serif",
        "weight_base": "800",
        "weight_emphasis": "400",
        "italic_emphasis": True,
        "accent": "#FFFFFF",
        "glow": "0 0 12px rgba(255,255,255,0.85), 0 0 24px rgba(255,255,255,0.45)",
        "shadow_base": "0 2px 8px rgba(0,0,0,0.65), 0 1px 2px rgba(0,0,0,0.5)",
        "scale_y": 1.08,
        "sample_html": '<span class="s11">teach you <em>everything</em></span>'
    },
    {
        "id": "style_10",
        "name": "Editorial Serif",
        "tagline": "Refined classic serif with micro/macro contrast",
        "description": "Timeless editorial look with alternating small particles and elegant serif words.",
        "font_family_base": "'Playfair Display', 'PP Editorial New', serif",
        "font_family_emphasis": "'Playfair Display', serif",
        "weight_base": "600",
        "weight_emphasis": "700",
        "italic_emphasis": True,
        "accent": "#F3F2F0",
        "glow": "none",
        "shadow_base": "0 2px 10px rgba(0,0,0,0.6)",
        "scale_y": 1.0,
        "sample_html": '<span class="s10"><small>the </small>timeless</span>'
    },
    {
        "id": "style_1",
        "name": "Bold Yellow",
        "tagline": "High-impact uppercase yellow pop",
        "description": "Punchy all-caps typography with thick stroke and electric yellow highlights.",
        "font_family_base": "'Montserrat', sans-serif",
        "font_family_emphasis": "'Montserrat', sans-serif",
        "weight_base": "900",
        "weight_emphasis": "900",
        "italic_emphasis": False,
        "accent": "#FFE600",
        "glow": "0 0 14px rgba(255,230,0,0.45)",
        "shadow_base": "0 3px 0 #000, 0 5px 12px rgba(0,0,0,0.6)",
        "scale_y": 1.0,
        "sample_html": '<span class="s1">EVERYTHING</span>'
    },
    {
        "id": "style_2",
        "name": "Cyan Pop",
        "tagline": "Modern TikTok / Reels bold white with cyan highlights",
        "description": "Thick geometric typography with vibrant neon cyan key phrase highlighting.",
        "font_family_base": "'Poppins', sans-serif",
        "font_family_emphasis": "'Poppins', sans-serif",
        "weight_base": "800",
        "weight_emphasis": "800",
        "italic_emphasis": False,
        "accent": "#00E5FF",
        "glow": "0 0 14px rgba(0,229,255,0.4)",
        "shadow_base": "0 2px 6px rgba(0,0,0,0.6)",
        "scale_y": 1.0,
        "sample_html": '<span class="s2">he knows <b>about</b></span>'
    },
    {
        "id": "style_3",
        "name": "Yellow Tag",
        "tagline": "Plus Jakarta Sans with soft yellow glow",
        "description": "Clean modern sans-serif with subtle warm yellow emphasis.",
        "font_family_base": "'Plus Jakarta Sans', sans-serif",
        "font_family_emphasis": "'Plus Jakarta Sans', sans-serif",
        "weight_base": "800",
        "weight_emphasis": "800",
        "italic_emphasis": False,
        "accent": "#FFE600",
        "glow": "0 0 10px rgba(255,230,0,0.4)",
        "shadow_base": "0 2px 6px rgba(0,0,0,0.6)",
        "scale_y": 1.0,
        "sample_html": '<span class="s3">he <b>knows</b> it</span>'
    },
    {
        "id": "style_4",
        "name": "Red Impact",
        "tagline": "Aggressive all-caps red glow",
        "description": "High adrenaline styling with sharp contrast and neon red aura.",
        "font_family_base": "'Montserrat', sans-serif",
        "font_family_emphasis": "'Montserrat', sans-serif",
        "weight_base": "900",
        "weight_emphasis": "900",
        "italic_emphasis": False,
        "accent": "#FF4154",
        "glow": "0 0 14px rgba(255,65,84,0.5)",
        "shadow_base": "0 2px 8px rgba(0,0,0,0.7)",
        "scale_y": 1.0,
        "sample_html": '<span class="s4">BOUNCE</span>'
    },
    {
        "id": "style_5",
        "name": "Cyan Minimal",
        "tagline": "Minimalist clean lower-case with cyan accents",
        "description": "Balanced sans-serif for storytellers, documentaries, and tech clips.",
        "font_family_base": "'Montserrat', sans-serif",
        "font_family_emphasis": "'Montserrat', sans-serif",
        "weight_base": "700",
        "weight_emphasis": "800",
        "italic_emphasis": False,
        "accent": "#00E5FF",
        "glow": "none",
        "shadow_base": "0 2px 4px rgba(0,0,0,0.5)",
        "scale_y": 1.0,
        "sample_html": '<span class="s5">herbs, <b>gardening</b></span>'
    },
    {
        "id": "style_6",
        "name": "Electric Blue",
        "tagline": "Deep blue drop glow with strong white text",
        "description": "Dynamic electric blue aura highlighting powerful keywords.",
        "font_family_base": "'Montserrat', sans-serif",
        "font_family_emphasis": "'Montserrat', sans-serif",
        "weight_base": "800",
        "weight_emphasis": "800",
        "italic_emphasis": False,
        "accent": "#00AAFF",
        "glow": "0 0 12px #0088ff",
        "shadow_base": "0 2px 6px rgba(0,0,0,0.6)",
        "scale_y": 1.0,
        "sample_html": '<span class="s6">he <b>knows</b></span>'
    },
    {
        "id": "style_7",
        "name": "Stack Script",
        "tagline": "Bold header stacked with handwriting script",
        "description": "Combines heavy grotesque capitals with organic handwritten calligraphy.",
        "font_family_base": "'Montserrat', sans-serif",
        "font_family_emphasis": "'Caveat', 'Alex Brush', cursive",
        "weight_base": "900",
        "weight_emphasis": "700",
        "italic_emphasis": True,
        "accent": "#FF3366",
        "glow": "none",
        "shadow_base": "0 2px 8px rgba(0,0,0,0.7)",
        "scale_y": 1.0,
        "sample_html": '<span class="s7"><span class="h">EVERYTHING</span><span class="sc">that he knows</span></span>'
    },
    {
        "id": "style_8",
        "name": "Inter Blue",
        "tagline": "Modern interface aesthetic with royal blue",
        "description": "Inter ExtraBold with crisp digital royal blue emphasis.",
        "font_family_base": "'Inter', sans-serif",
        "font_family_emphasis": "'Inter', sans-serif",
        "weight_base": "800",
        "weight_emphasis": "800",
        "italic_emphasis": False,
        "accent": "#3B82F6",
        "glow": "none",
        "shadow_base": "0 2px 6px rgba(0,0,0,0.5)",
        "scale_y": 1.0,
        "sample_html": '<span class="s8">just <b>anything</b></span>'
    },
    {
        "id": "style_9",
        "name": "Yellow Box",
        "tagline": "Highlighter marker box pill",
        "description": "Word highlighted with a rounded yellow background badge like a marker.",
        "font_family_base": "'Plus Jakarta Sans', sans-serif",
        "font_family_emphasis": "'Plus Jakarta Sans', sans-serif",
        "weight_base": "800",
        "weight_emphasis": "800",
        "italic_emphasis": False,
        "accent": "#FFE600",
        "glow": "none",
        "shadow_base": "0 2px 4px rgba(0,0,0,0.4)",
        "scale_y": 1.0,
        "is_pill": True,
        "sample_html": '<span class="s9"><mark>teach you</mark> all</span>'
    }
]

def get_style_by_id(style_id: str):
    for s in STYLES:
        if s["id"] == style_id:
            return s
    return STYLES[0]
